version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: vtexday26-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: vtexday26
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - vtexday26-network

  redis:
    image: redis:7-alpine
    container_name: vtexday26-redis
    restart: unless-stopped
    command: redis-server --requirepass redis123
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - vtexday26-network

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  vtexday26-network:
    driver: bridge